source 'https://rubygems.org'
gem 'highline', :require => 'highline/import'
gem 'clipboard', :require => 'clipboard'
require 'optparse'
require 'ostruct'
require 'digest'
require 'securerandom'
require 'base64'
