#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'
require_relative 'import/colortext'
require_relative 'import/magic'
require_relative 'import/passtrust'
Bundler.require(:default)
begin
  require 'clipboard'
rescue LoadError
  puts ColorText.new.red("Clipboard options disabled because of missing 'clipboard' gem.")
end

$options = OpenStruct.new

# default options
$version = "2.1.dev"
$options.length = 16
$options.timeout = 10

OptionParser.new do |opt|

  opt.banner = "  Passtrust Password Generator

  Usage: passtrust [options]"

  opt.on('-v', '--verify', 'Ask the passphrase twice') { $options.verify = true }
  opt.on('-l', '--length [length]', Integer, 'Change password length (min 16 max 64)') { |o| $options.length = o }
  opt.on('-t', '--timeout [seconds]', Integer, 'Change default timeout (10 seconds)') { |o| $options.timeout = o }
  opt.on('-c', '--clipboard', 'Copy generated password to clipboard') { $options.clipboard = true }
  opt.on('-r', '--random', 'Use a random passphrase') { $options.random = true }
  opt.on('-p', '--pass_security', 'Check security of passphrase') { $options.security = true }
  opt.on('-s', '--special', 'Replace some of the characters with specials') {$options.special = true }

  opt.on_tail('-h', '--help', 'Show this text') { puts opt; exit 130 }
  opt.on_tail('-V', '--version', 'Show version info and exit') { puts "Version: #{$version}"; exit 130 }

end.parse!

def leave
  length = $options.length
  if defined?(Clipboard)
    Clipboard.copy Magic.new.magic(SecureRandom.hex(16), length)
  end
  exit 130
end

def main
  Passtrust.new.start
end

if __FILE__ == $0
  trap "SIGINT" do
    puts "\r\nTerminated by user."
    begin; leave; rescue; exit 130; end
  end
  main
end
