#!${PREFIX}/bin/bash
apt install ruby
mkdir -p ${PREFIX}/share/passtrust
cp -a /data/data/com.termux/files/home/passtrust/* ${PREFIX}/share/passtrust
cd ${PREFIX}/share/passtrust
bundle install
cat > ${PREFIX}/bin/passtrust <<EOF
#!${PREFIX}/bin/bash
cd ${PREFIX}/share/passtrust
ruby passtrust "\$@"
EOF
chmod 755 ${PREFIX}/bin/passtrust
